Translation to brazilian portuguese
pop-os/system-updater pull request #21
Opened 2022-06-13 00:28 UTC by gustavosaquino

2022-06-13 12:41 UTC, mmstick approved these changes, later dismissed

2022-06-13 14:10 UTC, n3m0-22 requested changes
The translations look good, but I am not seeing them show up in the system-updater once installed. I have checked on two systems both set to Brazilian Portuguese.

2022-06-13 15:21 UTC, n3m0-22 commented
Renaming the directory `gtk/i18n/pt_BR/' to `gtk/i18n/pt-BR/' should fix the issue.

2022-06-14 01:35 UTC, n3m0-22 approved these changes
That fixed it. This looks good. Thank you.

2022-06-14 15:17 UTC, jackpot51 approved these changes

2022-06-14 15:17 UTC, merged